development:
  access_key_id: AKIAI4YTGPQPHYMTMT5Q
  secret_access_key: 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
  bucket: spacelender
production:
  access_key_id: AKIAI4YTGPQPHYMTMT5Q
  secret_access_key: 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
  bucket: spacelender